from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime

def create_legal_notice_doc(notice_text: str, case_id: str, issue_type: str) -> str:
    
    doc = Document()

    # Set standard 1-inch (2.54 cm) margins on all sides
    for section in doc.sections:
        section.top_margin = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)

    # Title - LEGAL NOTICE
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_title = title_para.add_run("LEGAL NOTICE")
    run_title.font.name = 'Times New Roman'
    run_title.font.size = Pt(16)
    run_title.font.bold = True
    run_title.font.color.rgb = RGBColor(0x8B, 0x00, 0x00) # Deep Crimson Red

    # Sub-header / Metadata
    meta_para = doc.add_paragraph()
    meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_meta = meta_para.add_run(
        f"Case ID: {case_id}   |   Category: {issue_type}   |   Date: {datetime.now().strftime('%d %B %Y')}"
    )
    run_meta.font.name = 'Times New Roman'
    run_meta.font.size = Pt(9.5)
    run_meta.font.italic = True
    run_meta.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    # Top border line
    border_para = doc.add_paragraph()
    border_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    border_para.add_run("━" * 55).font.color.rgb = RGBColor(0xBB, 0xBB, 0xBB)

    # Content body
    for line in notice_text.split("\n"):
        cleaned_line = line.strip()
        if not cleaned_line:
            # Add a small spacing paragraph for double spacing look
            p_space = doc.add_paragraph()
            p_space.paragraph_format.space_after = Pt(4)
            continue
            
        p = doc.add_paragraph()
        
        # Apply smart styling based on line contents
        if cleaned_line.upper().startswith(("LEGAL NOTICE", "SUBJECT:", "RE:", "TO,")) or cleaned_line.startswith(("Dear", "Sirs", "Madam")):
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            run = p.add_run(cleaned_line)
            run.font.bold = True
        elif cleaned_line.startswith(("-", "*", "•")) or (cleaned_line[0].isdigit() if cleaned_line and cleaned_line[0].isdigit() else False):
            p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            p.paragraph_format.left_indent = Inches(0.3)
            run = p.add_run(cleaned_line)
        else:
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            run = p.add_run(cleaned_line)

        # Style standard runs
        p.paragraph_format.line_spacing = 1.25
        p.paragraph_format.space_after = Pt(6)
        run.font.name = 'Times New Roman'
        run.font.size = Pt(11.5)
        run.font.color.rgb = RGBColor(0x11, 0x11, 0x11)

    # Bottom border line
    border_para2 = doc.add_paragraph()
    border_para2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    border_para2.add_run("━" * 55).font.color.rgb = RGBColor(0xBB, 0xBB, 0xBB)

    # Footer
    footer_para = doc.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_foot = footer_para.add_run("Generated by LegalEase — AI-Powered Legal Notice System & UiPath Orchestration")
    run_foot.font.name = 'Times New Roman'
    run_foot.font.size = Pt(8.5)
    run_foot.font.italic = True
    run_foot.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    filename = f"notice_{case_id}.docx"
    doc.save(filename)
    return filename